name: open-notebook
services:
  - name: frontend
    github:
      repo: YOUR_USERNAME/open-notebook
      branch: main
    build_command: cd frontend && npm install && npm run build
    run_command: cd frontend && npm start
    http_port: 8502
    envs:
      - key: API_URL
        value: ${backend.PUBLIC_URL}:5055
    health_check:
      http_path: /

  - name: backend
    github:
      repo: YOUR_USERNAME/open-notebook
      branch: main
    build_command: cd backend && pip install -r requirements.txt
    run_command: cd backend && uvicorn main:app --host 0.0.0.0 --port 5055
    http_port: 5055
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
      - key: SURREAL_URL
        value: ws://localhost:8000/rpc
      - key: SURREAL_USER
        value: root
      - key: SURREAL_PASSWORD
        scope: RUN_TIME
      - key: SURREAL_NAMESPACE
        value: open_notebook
      - key: SURREAL_DATABASE
        value: production
    health_check:
      http_path: /config
