name: open-notebook
services:
  - name: frontend
    github:
      repo: kivik-gpl/open-notebook
      branch: main
    dockerfile_path: Dockerfile.frontend
    http_port: 8502
    envs:
      - key: INTERNAL_API_URL
        value: http://${backend.PRIVATE_URL}:5055
      - key: API_URL
        value: https://${backend.PUBLIC_URL}

  - name: backend
    github:
      repo: kivik-gpl/open-notebook
      branch: main
    dockerfile_path: Dockerfile.backend
    http_port: 5055
    envs:
      - key: OPENAI_API_KEY
        type: SECRET
      - key: SURREAL_URL
        value: ws://localhost:8000/rpc
      - key: SURREAL_USER
        value: root
      - key: SURREAL_PASSWORD
        type: SECRET
      - key: SURREAL_NAMESPACE
        value: open_notebook
      - key: SURREAL_DATABASE
        value: production
