name: open-notebook
services:
  - name: frontend
    github:
      repo: kivik-gpl/open-notebook
      branch: main
    dockerfile_path: Dockerfile.frontend
    http_port: 8502
    envs:
      - key: INTERNAL_API_URL
        value: http://${backend.PRIVATE_URL}:5055
      - key: API_URL
        value: https://${backend.PUBLIC_URL}
  - name: backend    # ← Same indentation level as frontend
    github:
      repo: kivik-gpl/open-notebook
      branch: main
    dockerfile_path: Dockerfile.backend
    http_port: 5055
    env_file: /Docker.env
